language: scala
scala:
  - 2.10.2
  - 2.10.3
  - 2.10.4
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7
  
before_script:
  - mysql -e 'create database SlickBlog;'
  
test:
  adapter: mysql2
  database: myapp_test
  username: root
  password: root
  encoding: utf8
